---
swagger: "2.0"
info:
  description: |
      "This API can be used to Create and Return Assignments based on Tags, 
       API does require an API Key being sent with the request."
  version: "1.0.0"
  title: "Assignment API"
  termsOfService: ""
  contact:
    email: "sachin_doshi@msn.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "192.168.153.4:3000"
basePath: "/api/v1"
tags:
- name: "Assignment"
  description: "Assignment API"
schemes:
- "http"
paths:
  /Assignment:
    get:
      tags:
      - "Assignment"
      summary: "Get all Assignments"
      description: "Returns all Assignments"
      operationId: "getAllAssignments"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          sschema:
            type: "array"
            items:
              $ref: "#/definitions/Assignment"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Assignment not found"
        401:
          description: "Unauthorized - Need Correct API Key to Access APIs"
      security:
      - api_key: []
      x-swagger-router-controller: "Assignment"  
    post:
      summary: "Add a new Assignment"
      description: "Add an Assignment with its name, title and tags"
      operationId: "createAssignment"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Assignment object"
        required: true
        schema:
          $ref: "#/definitions/Assignment"
      responses:
        405:
          description: "Invalid input"
        409:
          description: "Duplicate key error"
        200:
          description: "successful operation"
          401:
            description: "Unauthorized - Need Correct API Key to Access APIs"        
      security:
        - api_key: []
      x-swagger-router-controller: "Default"
  /Assignment/findByTags:
    get:
      tags:
      - "Assignment"
      summary: "Finds Assignment by tags"
      description: |
          "Muliple tags can be provided with comma separated strings. e.g\
          .Use tag1, tag2, tag3 "
      operationId: "findAssignmentByTags"
      produces:
      - "application/json"
      parameters:
      - name: "tags"
        in: "query"
        description: "Tags to filter by"
        required: true
        type: "array"
        items:
          type: "string"
        collectionFormat: "multi"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Assignment"
        400:
          description: "Invalid tag value"
        401:
          description: "Unauthorized - Need Correct API Key to Access APIs"
      security:
        - api_key: []
      x-swagger-router-controller: "Assignment"
  /Assignment/{AssignmentId}:
    get:
      tags:
      - "Assignment"
      summary: "Find Assignment by ID"
      description: "Returns a single Assignment"
      operationId: "getAssignmentById"
      produces:
      - "application/json"
      parameters:
      - name: "AssignmentId"
        in: "path"
        description: "ID of Assignment to return"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Assignment"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Assignment not found"
        401:
          description: "Unauthorized - Need Correct API Key to Access APIs"
      security:
      - api_key: []
      x-swagger-router-controller: "Assignment"
    delete:
      tags:
      - "Assignment"
      summary: "Deletes an Assignment"
      description: ""
      operationId: "deleteAssignment"
      produces:
      - "application/json"
      parameters:
      - name: "AssignmentId"
        in: "path"
        description: "Assignment id to delete"
        required: true
        type: "string"        
      responses:
        400:
          description: "Invalid Assignment ID supplied"
        404:
          description: "Assignment not found"
        401:
          description: "Unauthorized - Need Correct API Key to Access APIs"
      security:
      - api_key: []
      x-swagger-router-controller: "Assignment"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "query"
definitions:
  Assignment:
    type: "object"
    required:
    - "Duration"
    - "Name"
    - "Tags"
    - "Type"
    properties:
      ID:
        type: "string"        
      Name:
        type: "string"
        example: "Introduction to AWS"
      Title:
        type: "string"
        example: "Introduction to AWS"
      Type:
        type: "string"
        example: "Cloud"
      Desc:
        type: "string"
        example: "Blah Blah Blah Blah Blah Blah Blah Blah ..."
      Duration:
        type: "string"
        example: "30Min"
      Tags:
        type: "array"
        example: ["AWS","CLOUD"]
        items:
          type: "string"
    example:
      Name: "Introduction to AWS"
      Type: "Cloud"
      Title: "Introduction to AWS"
      Duration: "30Min"
      Desc: "Learn AWS and Migrate workloads from your data center to AWS Cloud!"
      Tags: ["AWS","CLOUD"]

